- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Disable swap
      shell: swapoff -a
      args:
        warn: false

    - name: Remove swap file from fstab
      shell: sed -i '/swap/d' /etc/fstab

    - name: Enable required kernel modules
      shell: |
        echo "overlay" >> /etc/modules-load.d/containerd.conf
        echo "br_netfilter" >> /etc/modules-load.d/containerd.conf
        modprobe overlay
        modprobe br_netfilter

    - name: Configure sysctl for Kubernetes
      shell: |
        cat <<EOF > /etc/sysctl.d/kubernetes.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        EOF
        sysctl --system

    - name: Install required packages
      shell: |
        apt-get update
        apt-get install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates

    - name: Add Docker GPG key with automatic confirmation
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository with automatic confirmation
      shell: |
        yes | printf "\n" | add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install containerd with automatic confirmation
      shell: |
        yes | apt-get install -y containerd.io

    - name: Configure containerd
      shell: |
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd
        systemctl enable containerd

    - name: Add Kubernetes repository with automatic confirmation
      shell: |
        yes | echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
        yes | curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Install Kubernetes components with automatic confirmation
      shell: |
        yes | apt-get update
        yes | apt-get install -y kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl

- name: Setup Kubernetes Master Nodes
  hosts: masters
  become: true
  tasks:
    - name: Install Kubernetes Master Node components
      apt:
        name:
          - kubeadm
          - kubectl
        state: present
        update_cache: true

- name: Setup Kubernetes Worker Nodes
  hosts: workers
  become: true
  tasks:
    - name: Install Kubernetes Worker Node components
      apt:
        name:
          - kubelet
        state: present
        update_cache: true

- name: Generate and use Kubernetes join command
  hosts: masters
  become: true
  tasks:
    - name: Generate kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: localhost

    - name: Display the join command for debugging
      debug:
        msg: "{{ join_command.stdout }}"

    - name: Save the join command for workers
      set_fact:
        kubeadm_join_command: "{{ join_command.stdout }}"

- name: Join worker nodes to Kubernetes cluster
  hosts: workers
  become: true
  tasks:
    - name: Join the node to the Kubernetes cluster
